#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-String-Expand
Version  : 0.04
Release  : 14
URL      : https://cpan.metacpan.org/authors/id/P/PE/PEVANS/String-Expand-0.04.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/P/PE/PEVANS/String-Expand-0.04.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libs/libstring-expand-perl/libstring-expand-perl_0.04-3.debian.tar.xz
Summary  : |-
Group    : Development/Tools
License  : Artistic-1.0 Artistic-1.0-Perl GPL-1.0
Requires: perl-String-Expand-license = %{version}-%{release}
Requires: perl-String-Expand-perl = %{version}-%{release}
BuildRequires : buildreq-cpan
BuildRequires : perl(Sub::Uplevel)
BuildRequires : perl(Test::Exception)

%description
NAME
"String::Expand" - string utility functions for expanding variables in
self-referential sets

%package dev
Summary: dev components for the perl-String-Expand package.
Group: Development
Provides: perl-String-Expand-devel = %{version}-%{release}
Requires: perl-String-Expand = %{version}-%{release}

%description dev
dev components for the perl-String-Expand package.


%package license
Summary: license components for the perl-String-Expand package.
Group: Default

%description license
license components for the perl-String-Expand package.


%package perl
Summary: perl components for the perl-String-Expand package.
Group: Default
Requires: perl-String-Expand = %{version}-%{release}

%description perl
perl components for the perl-String-Expand package.


%prep
%setup -q -n String-Expand-0.04
cd %{_builddir}
tar xf %{_sourcedir}/libstring-expand-perl_0.04-3.debian.tar.xz
cd %{_builddir}/String-Expand-0.04
mkdir -p deblicense/
cp -r %{_builddir}/debian/* %{_builddir}/String-Expand-0.04/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/perl-String-Expand
cp %{_builddir}/String-Expand-0.04/LICENSE %{buildroot}/usr/share/package-licenses/perl-String-Expand/64cc2d010dde4fb9eba5bb43c0a9f855600f45b0
cp %{_builddir}/debian/copyright %{buildroot}/usr/share/package-licenses/perl-String-Expand/e30770f62ded31cf6292631d1c16dd36fe45f6f4
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/String::Expand.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/perl-String-Expand/64cc2d010dde4fb9eba5bb43c0a9f855600f45b0
/usr/share/package-licenses/perl-String-Expand/e30770f62ded31cf6292631d1c16dd36fe45f6f4

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/vendor_perl/5.32.1/String/Expand.pm
