#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-String-Expand
Version  : 0.04
Release  : 1
URL      : https://cpan.metacpan.org/authors/id/P/PE/PEVANS/String-Expand-0.04.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/P/PE/PEVANS/String-Expand-0.04.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libs/libstring-expand-perl/libstring-expand-perl_0.04-3.debian.tar.xz
Summary  : |-
Group    : Development/Tools
License  : Artistic-1.0 Artistic-1.0-Perl GPL-1.0
Requires: perl-String-Expand-license
Requires: perl-String-Expand-man
Requires: perl(Sub::Uplevel)
Requires: perl(Test::Exception)
BuildRequires : perl(Sub::Uplevel)
BuildRequires : perl(Test::Exception)

%description
NAME
"String::Expand" - string utility functions for expanding variables in
self-referential sets

%package license
Summary: license components for the perl-String-Expand package.
Group: Default

%description license
license components for the perl-String-Expand package.


%package man
Summary: man components for the perl-String-Expand package.
Group: Default

%description man
man components for the perl-String-Expand package.


%prep
tar -xf %{SOURCE1}
cd ..
%setup -q -n String-Expand-0.04
mkdir -p %{_topdir}/BUILD/String-Expand-0.04/deblicense/
mv %{_topdir}/BUILD/debian/* %{_topdir}/BUILD/String-Expand-0.04/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/perl-String-Expand
cp LICENSE %{buildroot}/usr/share/doc/perl-String-Expand/LICENSE
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/String/Expand.pm

%files license
%defattr(-,root,root,-)
/usr/share/doc/perl-String-Expand/LICENSE

%files man
%defattr(-,root,root,-)
/usr/share/man/man3/String::Expand.3
